"use client";

import React, { useState, useEffect } from "react";
import { WorkstationTuiMockup } from "./WorkstationTuiMockup";

interface FeatureStep {
  id: string;
  stepNumber: string;
  title: string;
  description: string;
}

const features: FeatureStep[] = [
  {
    id: "pin-pairing",
    stepNumber: "01",
    title: "Zero Port-Forwarding Pairing",
    description:
      "No port forwarding, ngrok tunnels, or complex VPN setups. Type a 6-digit ephemeral PIN generated by your local workstation CLI daemon to pair securely over an end-to-end WebSocket relay in 3 seconds.",
  },
  {
    id: "byok-vault",
    stepNumber: "02",
    title: "Client-Side BYOK Key Vault",
    description:
      "Bring Your Own API Keys with zero cloud retention. Store and switch Anthropic, OpenAI, DeepSeek, and Gemini credentials client-side with AES-256 encryption. Your keys never touch our servers.",
  },
  {
    id: "telemetry",
    stepNumber: "03",
    title: "Real-Time Token Telemetry",
    description:
      "Watch Claude, DeepSeek, and TrueForge agents generate code character-by-character with zero noticeable latency. Full AST syntax highlights, terminal pipes, and ANSI output straight in your pocket.",
  },
  {
    id: "safety-gate",
    stepNumber: "04",
    title: "1-Tap Human-in-the-Loop Approvals",
    description:
      "Never let an autonomous agent accidentally delete production files. Destructive bash executions and critical config edits pause at an encrypted 180s safety gate awaiting your explicit 1-tap mobile authorization.",
  },
  {
    id: "diff-inspector",
    stepNumber: "05",
    title: "Visual Git Diff & AST Viewer",
    description:
      "Review unified multi-file diffs before your agent commits. Line-by-line green additions, red deletions, and folded context blocks formatted cleanly for handheld mobile screens.",
  },
];

export function ScrollFeaturePhoneShowcase() {
  const [activeIndex, setActiveIndex] = useState<number>(0);
  const [countdown, setCountdown] = useState<number>(178);
  const [isApproved, setIsApproved] = useState<boolean>(false);
  const [isPaused, setIsPaused] = useState<boolean>(false);

  // Live PIN entering simulation for the first mobile screen
  const [typedPin, setTypedPin] = useState<string>("");
  const [isPairedSuccess, setIsPairedSuccess] = useState<boolean>(false);

  useEffect(() => {
    if (activeIndex !== 0) return;
    const TARGET_PIN = "834192";
    let step = 0;
    setTypedPin("");
    setIsPairedSuccess(false);

    const typeInterval = setInterval(() => {
      step++;
      if (step <= TARGET_PIN.length) {
        setTypedPin(TARGET_PIN.slice(0, step));
        if (step === TARGET_PIN.length) {
          setIsPairedSuccess(true);
        }
      } else if (step > TARGET_PIN.length + 5) {
        step = 0;
        setTypedPin("");
        setIsPairedSuccess(false);
      }
    }, 460);

    return () => clearInterval(typeInterval);
  }, [activeIndex]);

  // 180s countdown simulation for Safety Gate
  useEffect(() => {
    if (isApproved) return;
    const timer = setInterval(() => {
      setCountdown((prev) => (prev > 1 ? prev - 1 : 180));
    }, 1000);
    return () => clearInterval(timer);
  }, [isApproved]);

  // Auto-advance every 8 seconds when user is not manually hovering
  useEffect(() => {
    if (isPaused) return;
    const interval = setInterval(() => {
      setActiveIndex((prev) => (prev + 1) % features.length);
    }, 8000);
    return () => clearInterval(interval);
  }, [isPaused]);

  const handleApprove = () => {
    setIsApproved(true);
    setTimeout(() => setIsApproved(false), 4000);
  };

  const handlePrev = () => {
    setActiveIndex((prev) => (prev > 0 ? prev - 1 : features.length - 1));
  };

  const handleNext = () => {
    setActiveIndex((prev) => (prev + 1) % features.length);
  };

  return (
    <section
      id="features"
      style={styles.showcaseSection}
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      {/* Main Presentation Container (2 Columns: Left Header + Ladder | Right Phone Mockup) */}
      <div style={styles.stageGrid}>
        {/* LEFT COLUMN: Header + 3-Stair Vertical Ladder */}
        <div style={styles.leftColumn}>
          {/* Left-Aligned Header */}
          <div style={styles.headerContainer}>
            <h2 style={styles.mainTitle}>
              Your Autonomous Agent <br />
              In The Palm of Your Hand.
            </h2>
            <p style={styles.mainSubtitle}>
              Explore the core mobile surfaces designed for high-speed supervision from anywhere.
            </p>
          </div>

          {/* 3-Stair Vertical Ladder (Active unfaded, upper & lower faded) */}
          <div style={styles.ladderColumn}>
            {/* Vertical Staircase Progress Line */}
            <div style={styles.ladderRail}>
              <div
                style={{
                  ...styles.ladderRailIndicator,
                  top: `${(activeIndex / (features.length - 1)) * 82}%`,
                }}
              />
            </div>

            {/* Feature Stair Ladder Items */}
            <div style={styles.ladderItemsWrapper}>
              {features.map((feature, idx) => {
                const isActive = activeIndex === idx;
                const isUpper = idx < activeIndex;
                const isLower = idx > activeIndex;

                return (
                  <button
                    key={feature.id}
                    type="button"
                    onClick={() => setActiveIndex(idx)}
                    style={{
                      ...styles.ladderItem,
                      ...(isActive
                        ? styles.ladderItemActive
                        : isUpper
                        ? styles.ladderItemUpper
                        : isLower
                        ? styles.ladderItemLower
                        : {}),
                    }}
                  >
                    <div style={styles.itemHeaderRow}>
                      <span
                        style={{
                          ...styles.stepNumberText,
                          color: isActive ? "#2563eb" : "#94a3b8",
                        }}
                      >
                        {feature.stepNumber}
                      </span>
                    </div>

                    <h3
                      style={{
                        ...styles.ladderTitle,
                        ...(isActive ? styles.ladderTitleActive : styles.ladderTitleFaded),
                      }}
                    >
                      {feature.title}
                    </h3>

                    {isActive && (
                      <div style={styles.activeDetailBox}>
                        <p style={styles.ladderDescription}>{feature.description}</p>
                      </div>
                    )}
                  </button>
                );
              })}

              {/* Step Switcher Controls */}
              <div style={styles.stepControlsRow}>
                <button
                  type="button"
                  onClick={handlePrev}
                  style={styles.navArrowBtn}
                  title="Previous Feature"
                >
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <path d="M19 12H5M12 19l-7-7 7-7" />
                  </svg>
                </button>
                <div style={styles.pillsList}>
                  {features.map((_, dotIdx) => (
                    <button
                      key={dotIdx}
                      type="button"
                      onClick={() => setActiveIndex(dotIdx)}
                      style={{
                        ...styles.stepDot,
                        ...(activeIndex === dotIdx ? styles.stepDotActive : {}),
                      }}
                      title={`Feature ${dotIdx + 1}`}
                    />
                  ))}
                </div>
                <button
                  type="button"
                  onClick={handleNext}
                  style={styles.navArrowBtn}
                  title="Next Feature"
                >
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <path d="M5 12h14M12 5l7 7-7 7" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* RIGHT: Diagonal Duo Showcase (Workstation Local TUI + iOS Phone Remote Mockup) */}
        <div style={styles.duoStageColumn}>
          {/* Workstation Local Daemon TUI Window (Diagonally Behind) */}
          <div style={styles.tuiWrapperDiagonal}>
            <WorkstationTuiMockup
              activeIndex={activeIndex}
              typedPin={typedPin}
              isPairedSuccess={isPairedSuccess}
              isApproved={isApproved}
              countdown={countdown}
            />
          </div>

          {/* Authentic iOS iPhone Device Frame (Foreground) */}
          <div style={styles.phoneDeviceFrame}>
            {/* Dynamic Island Notch */}
            <div style={styles.dynamicIsland}>
              <div style={styles.cameraLens} />
              <div style={styles.sensorDot} />
            </div>

            {/* iOS Status Bar */}
            <div style={styles.phoneStatusBar}>
              <span style={styles.statusTime}>9:41</span>
              <div style={styles.statusIcons}>
                {/* 4 iOS Signal Bars */}
                <div style={styles.iosSignalBars}>
                  <span style={{ ...styles.signalBar, height: 4 }} />
                  <span style={{ ...styles.signalBar, height: 6 }} />
                  <span style={{ ...styles.signalBar, height: 8 }} />
                  <span style={{ ...styles.signalBar, height: 10 }} />
                </div>
                {/* Wi-Fi Icon */}
                <svg width="13" height="10" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 3c-4.97 0-9 4.03-9 9 0 2.12.74 4.07 1.97 5.61L4.35 18.97c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0l1.36-1.36C8.67 19.64 10.26 20 12 20c4.97 0 9-4.03 9-9s-4.03-9-9-9z" />
                </svg>
                {/* iOS Battery with Outline & Terminal */}
                <div style={styles.iosBatteryContainer}>
                  <div style={styles.iosBatteryOutline}>
                    <div style={styles.iosBatteryFill} />
                  </div>
                  <div style={styles.iosBatteryTip} />
                </div>
              </div>
            </div>

            {/* Mobile Screen Interior with Real Wallpaper Artwork */}
            <div style={styles.phoneScreenContent}>
              {/* Wallpaper Background Artwork */}
              <div style={styles.phoneScreenArtwork} />
              <div style={styles.phoneScreenArtworkOverlay} />

              {/* Screen Contents Layer */}
              <div style={styles.phoneScreenInner}>
                {/* ========================================================= */}
                {/* SCREEN 1: PIN PAIRING (Screenshot 1 Match)               */}
                {/* ========================================================= */}
                {activeIndex === 0 && (
                  <div key="screen-0" style={styles.fullScreenWrapper}>
                    {/* Top Row: • WebSocket E2E & ••• */}
                    <div style={styles.screen1TopRow}>
                      <div style={styles.e2eBadgePill}>
                        <span style={styles.whiteDotMini} />
                        <span>WebSocket E2E</span>
                      </div>
                      <div style={styles.threeDotsCircle}>•••</div>
                    </div>

                    {/* Centered Brand Title & Subtitle */}
                    <div style={styles.brandCenterHeader}>
                      <h4 style={styles.brandAirlinkTitle}>AirLink</h4>
                      <p style={styles.brandAirlinkSubtitle}>
                        Control your local coding agent from your phone with zero port-forwarding.
                      </p>
                    </div>

                    {/* Frosted Glass PIN Card */}
                    <div style={styles.pinCardExact}>
                      <div style={styles.pinCardTitle}>Workstation Session PIN</div>
                      <div style={styles.pinCardSubtitle}>
                        {isPairedSuccess ? "✓ Paired to Workstation Daemon" : "Enter 6-digit PIN from terminal"}
                      </div>

                      {/* 6 Discrete Boxes */}
                      <div style={styles.pinBoxesRow}>
                        {[0, 1, 2, 3, 4, 5].map((dIdx) => {
                          const digit = typedPin[dIdx] || "";
                          const isActiveBox = typedPin.length === dIdx && !isPairedSuccess;

                          return (
                            <div
                              key={dIdx}
                              style={{
                                ...styles.pinBox,
                                ...(isActiveBox ? styles.pinBoxActive : {}),
                                ...(digit ? styles.pinBoxFilled : {}),
                                ...(isPairedSuccess ? styles.pinBoxSuccess : {}),
                              }}
                            >
                              {digit ? (
                                <span>{digit}</span>
                              ) : isActiveBox ? (
                                <span style={styles.blinkingCaret}>|</span>
                              ) : null}
                            </div>
                          );
                        })}
                      </div>

                      <div style={styles.pinCardFooter}>
                        <span>✧ Ephemeral session • Auto-expires</span>
                      </div>
                    </div>

                    {/* Wide Connect Button */}
                    <div
                      style={{
                        ...styles.connectBtnWide,
                        ...(isPairedSuccess ? styles.connectBtnWideSuccess : {}),
                      }}
                    >
                      {isPairedSuccess ? "Connected to Workstation ✓" : "Connect to Workstation →"}
                    </div>

                    {/* Telemetry Strip & Green Active Pill */}
                    <div style={styles.screen1BottomBlock}>
                      <div style={styles.telemetryCardFrosted}>
                        <div style={styles.telemetryRow}>
                          <span style={styles.telemetryLabel}>WebSocket Relay:</span>
                          <span style={styles.telemetryValue}>sub-50ms (Direct)</span>
                        </div>
                        <div style={styles.telemetryRow}>
                          <span style={styles.telemetryLabel}>Security:</span>
                          <span style={styles.telemetryValue}>E2E Encrypted</span>
                        </div>
                      </div>

                      <div style={styles.greenRelayActivePill}>
                        <span style={styles.greenDotSmall} />
                        <span>WebSocket Relay Active</span>
                      </div>

                      <div style={styles.relayUrlSubtext}>
                        ▾ Relay: https://airlink-relay.onrender.com
                      </div>

                      <div style={styles.footerBrandSubtext}>
                        AirLink Universal Agent Remote • Zero Retention
                      </div>
                    </div>
                  </div>
                )}

                {/* ========================================================= */}
                {/* SCREEN 2: BYOK KEY VAULT (Screenshot 3 Match)            */}
                {/* ========================================================= */}
                {activeIndex === 1 && (
                  <div key="screen-1" style={styles.fullScreenWrapper}>
                    {/* Header Card */}
                    <div style={styles.byokHeaderCard}>
                      <div style={styles.byokHeaderLeft}>
                        <span style={{ fontSize: 20 }}>🔒</span>
                        <div>
                          <div style={styles.byokHeaderTitle}>Client-Side BYOK Vault</div>
                          <div style={styles.byokHeaderSubtitle}>Zero Cloud Retention</div>
                        </div>
                      </div>
                      <div style={styles.byokHeaderRight}>
                        <span style={styles.aesPill}>AES-256</span>
                        <span style={styles.doneBtnPill}>Done</span>
                      </div>
                    </div>

                    {/* Content Form Scroll */}
                    <div style={styles.byokFormSection}>
                      {/* Section 1: CONFIGURE PROVIDER */}
                      <div style={styles.byokSectionLabel}>CONFIGURE PROVIDER</div>
                      <div style={styles.providerPillsStack}>
                        <div style={styles.providerRow}>
                          <div style={styles.providerPill}>OpenRouter / 0x</div>
                          <div style={styles.providerPillSelected}>Google Gemini</div>
                        </div>
                        <div style={styles.providerRow}>
                          <div style={styles.providerPill}>Anthropic Claude</div>
                          <div style={styles.providerPill}>OpenAI</div>
                          <div style={styles.providerPill}>Groq Llama</div>
                        </div>
                        <div style={styles.providerRow}>
                          <div style={styles.providerPill}>Custom / Local</div>
                        </div>
                      </div>

                      {/* Section 2: MODEL IDENTIFIER */}
                      <div style={{ ...styles.byokSectionLabel, marginTop: 8 }}>MODEL IDENTIFIER</div>
                      <div style={styles.byokInputBox}>gemini-3.5-flash</div>
                      <div style={styles.modelChipsRow}>
                        <div style={styles.modelChip}>gemini-2.0-flash</div>
                        <div style={styles.modelChip}>gemini-1.5-pro</div>
                      </div>

                      {/* Section 3: API KEY */}
                      <div style={{ ...styles.byokSectionLabel, marginTop: 8 }}>API KEY</div>
                      <div style={styles.byokKeyInputBox}>
                        <span style={styles.keyDots}>•••••••••••••••••••••••••••••••••••••</span>
                        <span style={styles.keyShowBtn}>Show</span>
                      </div>
                      <p style={styles.keySecurityNote}>
                        Keys are stored in your device&apos;s secure vault (hardware keychain on iOS/Android, client storage on Web) and never persisted to the cloud relay.
                      </p>
                    </div>

                    {/* Bottom Buttons */}
                    <div style={styles.byokBottomActions}>
                      <button type="button" style={styles.saveConfigBtn}>
                        Save Configuration
                      </button>
                      <button type="button" style={styles.clearKeyBtn}>
                        Clear Key
                      </button>
                    </div>
                  </div>
                )}

                {/* ========================================================= */}
                {/* SCREEN 3: REAL-TIME TOKEN TELEMETRY (Screenshot 2 Match) */}
                {/* ========================================================= */}
                {activeIndex === 2 && (
                  <div key="screen-2" style={styles.chatScreenWrapper}>
                    {/* Top Header: AirLink Remote */}
                    <div style={styles.chatScreenHeader}>
                      <div style={styles.chatHeaderLeft}>
                        <div style={styles.chatHeaderTitle}>AirLink Remote</div>
                        <div style={styles.chatHeaderSubtitle}>Tyra • C:\Users\Tyra\age...</div>
                      </div>
                      <div style={styles.chatHeaderRight}>
                        <div style={styles.chatModelPill}>gemini-3.5-flash</div>
                        <div style={styles.chatCloseBtn}>✕</div>
                      </div>
                    </div>

                    {/* Conversation Feed (Screenshot 2 exact components) */}
                    <div style={styles.chatFeedScroll}>
                      {/* Thinking Box */}
                      <div style={styles.thinkingCard}>
                        <div style={styles.thinkingHeader}>
                          <div style={styles.thinkingTitleRow}>
                            <span>Thinking...</span>
                            <span style={{ fontSize: 9 }}>˅</span>
                          </div>
                          <span style={styles.thinkingCollapse}>Collapse</span>
                        </div>
                        <div style={styles.thinkingDirective}>
                          Analyzing directive: &quot;Check git status and explain modified files.&quot;
                        </div>
                      </div>

                      {/* Agent Explanation Prose (Directly on canvas) */}
                      <div style={styles.agentProseMessage}>
                        I will retrieve the current uncommitted git changes in the workspace using the{" "}
                        <code style={styles.inlineCodePill}>get_git_diff</code> tool to see what files are currently modified.
                      </div>

                      {/* Tool Execution Card */}
                      <div style={styles.toolExecCard}>
                        <div style={styles.toolExecHeader}>
                          <div style={styles.toolNameBadge}>get_git_diff</div>
                          <div style={styles.toolExecStatus}>Executing...</div>
                        </div>
                        <div style={styles.toolExecBody}>
                          Executing get_git_diff
                        </div>
                      </div>

                      {/* Code Diff Card with Jump to Live */}
                      <div style={styles.codeDiffCard}>
                        <div style={styles.codeDiffHeader}>
                          <div style={styles.codeDiffFileName}>vitest.config.ts</div>
                          <div style={styles.codeDiffStats}>
                            <span style={styles.badgeAdd}>+18</span>
                            <span style={styles.badgeDel}>-1</span>
                          </div>
                        </div>

                        <div style={styles.codeDiffView}>
                          <div style={styles.diffHeaderLine}>@@ -5,6 +5,7 @@ import * as fs from &quot;node:fs&quot;;</div>
                          <div style={styles.diffCodeLine}>import * as path from &quot;node:path&quot;;</div>
                          <div style={styles.diffCodeLine}>import * as crypto from &quot;node:crypto&quot;;</div>
                          <div style={styles.diffCodeLine}>import chalk from &quot;chalk&quot;;</div>
                          <div style={styles.diffCodeLineAdd}>+ import boxen from &quot;boxen&quot;;</div>
                          <div style={styles.diffCodeLine}>import dotenv from &quot;dotenv&quot;;</div>
                          <div style={styles.diffCodeLine}>import &#123;</div>
                        </div>

                        {/* Floating Jump to Live Pill */}
                        <div style={styles.jumpToLiveFloat}>
                          <span>↓ Jump to Live</span>
                        </div>
                      </div>
                    </div>

                    {/* Bottom Dock: Suggestion Pills directly ABOVE Text Input Bar */}
                    <div style={styles.chatBottomDock}>
                      {/* Suggestion Pills / Quick Action Chips */}
                      <div style={styles.quickChipsRow}>
                        <div style={styles.quickChip}>Create PR</div>
                        <div style={styles.quickChip}>Import Issue</div>
                        <div style={styles.quickChip}>Run Tests</div>
                        <div style={styles.quickChip}>Git Sta...</div>
                      </div>

                      {/* Handheld Bottom Prompt Input Bar */}
                      <div style={styles.promptInputContainer}>
                        <div style={styles.promptPlaceholder}>
                          Ask agent to build, refactor, or fix...
                        </div>
                        <div style={styles.promptSendArrow}>→</div>
                      </div>
                    </div>
                  </div>
                )}

                {/* ========================================================= */}
                {/* SCREEN 4: 1-TAP HUMAN APPROVALS                         */}
                {/* ========================================================= */}
                {activeIndex === 3 && (
                  <div key="screen-3" style={styles.chatScreenWrapper}>
                    {/* Top Header */}
                    <div style={styles.chatScreenHeader}>
                      <div style={styles.chatHeaderLeft}>
                        <div style={styles.chatHeaderTitle}>AirLink Remote</div>
                        <div style={styles.chatHeaderSubtitle}>Tyra • C:\Users\Tyra\age...</div>
                      </div>
                      <div style={styles.chatHeaderRight}>
                        <div style={styles.chatModelPill}>gemini-3.5-flash</div>
                        <div style={styles.chatCloseBtn}>✕</div>
                      </div>
                    </div>

                    <div style={styles.chatFeedScroll}>
                      {/* Thinking Box */}
                      <div style={styles.thinkingCard}>
                        <div style={styles.thinkingHeader}>
                          <div style={styles.thinkingTitleRow}>
                            <span>Thinking...</span>
                            <span style={{ fontSize: 9 }}>˅</span>
                          </div>
                          <span style={styles.thinkingCollapse}>Collapse</span>
                        </div>
                        <div style={styles.thinkingDirective}>
                          Analyzing directive: &quot;Purge build artifacts and verify production release.&quot;
                        </div>
                      </div>

                      {/* Agent Message */}
                      <div style={styles.agentProseMessage}>
                        Detected high-risk file purge command. Intercepting execution at the Safety Gate for your 1-tap mobile approval.
                      </div>

                      {/* Tool Call Card */}
                      <div style={styles.toolExecCard}>
                        <div style={styles.toolExecHeader}>
                          <div style={styles.toolNameBadge}>execute_bash</div>
                          <div style={{ ...styles.toolExecStatus, color: "#f59e0b" }}>Paused at Gate</div>
                        </div>
                        <div style={styles.toolExecBody}>
                          rm -rf dist/ &amp;&amp; pnpm build:prod
                        </div>
                      </div>

                      {/* Safety Gate Interception Card */}
                      <div style={styles.safetyGateCard}>
                        <div style={styles.safetyGateHeader}>
                          <div style={styles.safetyGateTitle}>
                            <span>⚠️</span>
                            <span>Safety Gate Interception</span>
                          </div>
                          <div style={styles.safetyCountdownBadge}>{countdown}s Gate</div>
                        </div>

                        <div style={styles.safetyCommandBox}>
                          <code>rm -rf dist/ &amp;&amp; pnpm build:prod</code>
                        </div>

                        {isApproved ? (
                          <div style={styles.approvedBanner}>
                            ✓ Command Authorized &amp; Executing...
                          </div>
                        ) : (
                          <div style={styles.approvalButtons}>
                            <button
                              type="button"
                              onClick={handleApprove}
                              style={styles.btnApprove}
                            >
                              Approve (1-Tap)
                            </button>
                            <button type="button" style={styles.btnReject}>
                              Reject
                            </button>
                          </div>
                        )}
                      </div>
                    </div>

                    {/* Bottom Dock: Suggestion Pills ABOVE Input Bar */}
                    <div style={styles.chatBottomDock}>
                      <div style={styles.quickChipsRow}>
                        <div style={styles.quickChip}>Create PR</div>
                        <div style={styles.quickChip}>Import Issue</div>
                        <div style={styles.quickChip}>Run Tests</div>
                        <div style={styles.quickChip}>Git Sta...</div>
                      </div>

                      <div style={styles.promptInputContainer}>
                        <div style={styles.promptPlaceholder}>
                          Ask agent to build, refactor, or fix...
                        </div>
                        <div style={styles.promptSendArrow}>→</div>
                      </div>
                    </div>
                  </div>
                )}

                {/* ========================================================= */}
                {/* SCREEN 5: VISUAL GIT DIFF & AST VIEWER                   */}
                {/* ========================================================= */}
                {activeIndex === 4 && (
                  <div key="screen-4" style={styles.chatScreenWrapper}>
                    {/* Top Header */}
                    <div style={styles.chatScreenHeader}>
                      <div style={styles.chatHeaderLeft}>
                        <div style={styles.chatHeaderTitle}>AirLink Remote</div>
                        <div style={styles.chatHeaderSubtitle}>Tyra • C:\Users\Tyra\age...</div>
                      </div>
                      <div style={styles.chatHeaderRight}>
                        <div style={styles.chatModelPill}>gemini-3.5-flash</div>
                        <div style={styles.chatCloseBtn}>✕</div>
                      </div>
                    </div>

                    <div style={styles.chatFeedScroll}>
                      {/* Thinking Box */}
                      <div style={styles.thinkingCard}>
                        <div style={styles.thinkingHeader}>
                          <div style={styles.thinkingTitleRow}>
                            <span>Thinking...</span>
                            <span style={{ fontSize: 9 }}>˅</span>
                          </div>
                          <span style={styles.thinkingCollapse}>Collapse</span>
                        </div>
                        <div style={styles.thinkingDirective}>
                          Analyzing directive: &quot;Make hero text all black with GSAP appearing reveal.&quot;
                        </div>
                      </div>

                      {/* Agent Explanation */}
                      <div style={styles.agentProseMessage}>
                        I am applying the GSAP word blur-reveal animation to PanoramicLandscapeHero.tsx and updating the context logs.
                      </div>

                      {/* Files Summary Strip */}
                      <div style={styles.filesSummaryCard}>
                        <div style={styles.filesSummaryTop}>
                          <div style={styles.filesSummaryLeft}>
                            <span>2 files changed</span>
                            <span style={styles.badgeAdd}>+92</span>
                            <span style={styles.badgeDel}>-35</span>
                          </div>
                          <div style={styles.reviewBtn}>[ Review ]</div>
                        </div>
                        <div style={styles.filesListStack}>
                          <div style={styles.fileRowItem}>
                            <span>⚛️</span>
                            <span style={styles.fileNameWhite}>PanoramicLandscapeHero.tsx</span>
                          </div>
                          <div style={styles.fileRowItem}>
                            <span>M↓</span>
                            <span style={styles.fileNameWhite}>progress-tracker.md</span>
                          </div>
                        </div>
                      </div>

                      {/* Diff Viewer Card */}
                      <div style={styles.codeDiffCard}>
                        <div style={styles.codeDiffHeader}>
                          <div style={styles.codeDiffFileName}>PanoramicLandscapeHero.tsx</div>
                          <div style={styles.codeDiffStats}>
                            <span style={styles.badgeAdd}>+92</span>
                            <span style={styles.badgeDel}>-35</span>
                          </div>
                        </div>

                        <div style={styles.codeDiffView}>
                          <div style={styles.diffHeaderLine}>@@ -40,8 +40,10 @@ export function PanoramicLandscapeHero() &#123;</div>
                          <div style={styles.diffCodeLineDel}>- color: &quot;transparent&quot;, backgroundClip: &quot;text&quot;,</div>
                          <div style={styles.diffCodeLineAdd}>+ color: &quot;#0f172a&quot;, fontWeight: 900,</div>
                          <div style={styles.diffCodeLineAdd}>+ gsap.fromTo(&quot;.hero-word&quot;, &#123; filter: &quot;blur(12px)&quot;, y: 48 &#125;,</div>
                          <div style={styles.diffCodeLine}>&nbsp;&nbsp;&#123; filter: &quot;blur(0px)&quot;, y: 0, stagger: 0.065 &#125;);</div>
                        </div>

                        <div style={styles.jumpToLiveFloat}>
                          <span>↓ Jump to Live</span>
                        </div>
                      </div>
                    </div>

                    {/* Bottom Dock: Suggestion Pills ABOVE Input Bar */}
                    <div style={styles.chatBottomDock}>
                      <div style={styles.quickChipsRow}>
                        <div style={styles.quickChip}>Create PR</div>
                        <div style={styles.quickChip}>Import Issue</div>
                        <div style={styles.quickChip}>Run Tests</div>
                        <div style={styles.quickChip}>Git Sta...</div>
                      </div>

                      <div style={styles.promptInputContainer}>
                        <div style={styles.promptPlaceholder}>
                          Ask agent to build, refactor, or fix...
                        </div>
                        <div style={styles.promptSendArrow}>→</div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* iOS Home Indicator Bar */}
            <div style={styles.iosHomeIndicator} />
          </div>
        </div>
      </div>
    </section>
  );
}

const styles: Record<string, React.CSSProperties> = {
  showcaseSection: {
    backgroundColor: "#ffffff",
    color: "#0f172a",
    padding: "60px 24px 60px",
    position: "relative",
    zIndex: 10,
    borderTop: "1px solid #f1f5f9",
    fontFamily: "var(--font-sans)",
  },
  stageGrid: {
    maxWidth: 1260,
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "1fr 1.15fr",
    gap: 40,
    alignItems: "center",
  },
  leftColumn: {
    display: "flex",
    flexDirection: "column",
    gap: 32,
  },
  headerContainer: {
    maxWidth: "100%",
    margin: 0,
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 12,
  },
  mainTitle: {
    fontFamily: "var(--font-display)",
    fontSize: "clamp(32px, 3.8vw, 48px)",
    fontWeight: 900,
    lineHeight: 1.12,
    letterSpacing: "-0.03em",
    color: "#0f172a",
    margin: 0,
  },
  mainSubtitle: {
    fontFamily: "var(--font-sans)",
    fontSize: "clamp(15px, 1.35vw, 17px)",
    color: "#475569",
    lineHeight: 1.6,
    maxWidth: 520,
    fontWeight: 450,
    margin: 0,
  },
  ladderColumn: {
    display: "flex",
    alignItems: "flex-start",
    gap: 26,
    minHeight: 440,
    position: "relative",
  },
  ladderRail: {
    width: 2,
    height: 320,
    backgroundColor: "#e2e8f0",
    borderRadius: 9999,
    position: "relative",
    marginTop: 14,
    flexShrink: 0,
  },
  ladderRailIndicator: {
    position: "absolute",
    left: -4,
    width: 10,
    height: 36,
    backgroundColor: "#2563eb",
    borderRadius: 9999,
    transition: "top 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
  },
  ladderItemsWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
    width: "100%",
  },
  ladderItem: {
    cursor: "pointer",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
    backgroundColor: "transparent",
    border: "none",
    padding: 0,
    outline: "none",
    font: "inherit",
    width: "100%",
  },
  ladderItemActive: {
    opacity: 1,
    transform: "translateY(0) scale(1)",
  },
  ladderItemUpper: {
    opacity: 0.28,
    transform: "translateY(-4px) scale(0.95)",
    filter: "blur(0.4px)",
  },
  ladderItemLower: {
    opacity: 0.28,
    transform: "translateY(4px) scale(0.95)",
    filter: "blur(0.4px)",
  },
  itemHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 5,
  },
  stepNumberText: {
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: 0.5,
  },
  ladderTitle: {
    fontFamily: "var(--font-display)",
    margin: 0,
    lineHeight: 1.2,
    letterSpacing: "-0.025em",
  },
  ladderTitleActive: {
    fontSize: "clamp(26px, 2.5vw, 33px)",
    fontWeight: 900,
    color: "#0f172a",
  },
  ladderTitleFaded: {
    fontSize: "clamp(18px, 1.8vw, 21px)",
    fontWeight: 700,
    color: "#64748b",
  },
  activeDetailBox: {
    marginTop: 10,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    animation: "fadeIn 0.25s ease-out",
  },
  ladderDescription: {
    fontFamily: "var(--font-sans)",
    fontSize: 15,
    color: "#475569",
    lineHeight: 1.65,
    maxWidth: 520,
    fontWeight: 450,
  },
  stepControlsRow: {
    marginTop: 14,
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  navArrowBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
    borderRadius: "50%",
    backgroundColor: "#f1f5f9",
    border: "1px solid #e2e8f0",
    color: "#334155",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  pillsList: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  stepDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    backgroundColor: "#cbd5e1",
    border: "none",
    padding: 0,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  stepDotActive: {
    width: 24,
    backgroundColor: "#2563eb",
    borderRadius: 9999,
  },

  /* Duo Stage Column */
  duoStageColumn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    width: "100%",
    padding: "10px 0",
  },
  tuiWrapperDiagonal: {
    position: "relative",
    marginRight: "-68px",
    zIndex: 1,
    transform: "translateY(-14px) rotate(-1.5deg)",
    transition: "all 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
    maxWidth: 340,
    width: "100%",
  },

  /* Device Frame (iOS Titanium) */
  phoneDeviceFrame: {
    position: "relative",
    zIndex: 2,
    width: 304,
    height: 618,
    backgroundColor: "#000000",
    borderRadius: 44,
    border: "9px solid #1e293b",
    boxShadow: "-14px 28px 70px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.12)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    transform: "translateY(10px) rotate(1deg)",
    transition: "all 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
    fontFamily: "var(--font-sans)",
  },
  dynamicIsland: {
    position: "absolute",
    top: 8,
    left: "50%",
    transform: "translateX(-50%)",
    width: 82,
    height: 22,
    backgroundColor: "#000000",
    borderRadius: 20,
    zIndex: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 11px",
  },
  cameraLens: {
    width: 7.5,
    height: 7.5,
    borderRadius: "50%",
    backgroundColor: "#1e293b",
  },
  sensorDot: {
    width: 4,
    height: 4,
    borderRadius: "50%",
    backgroundColor: "#0f172a",
  },
  phoneStatusBar: {
    height: 38,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 22px 0 20px",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: 700,
    zIndex: 20,
    backgroundColor: "transparent",
  },
  statusTime: {
    fontFamily: "var(--font-sans)",
    fontSize: 12.5,
    fontWeight: 700,
    letterSpacing: "-0.015em",
  },
  statusIcons: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  iosSignalBars: {
    display: "flex",
    alignItems: "flex-end",
    gap: 1.5,
    height: 10,
  },
  signalBar: {
    width: 2.2,
    backgroundColor: "#ffffff",
    borderRadius: 0.5,
  },
  iosBatteryContainer: {
    display: "flex",
    alignItems: "center",
    gap: 1,
  },
  iosBatteryOutline: {
    width: 18,
    height: 10,
    border: "1.2px solid #ffffff",
    borderRadius: 3,
    padding: 1,
    display: "flex",
    alignItems: "center",
  },
  iosBatteryFill: {
    width: "75%",
    height: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 1.5,
  },
  iosBatteryTip: {
    width: 1.5,
    height: 4,
    backgroundColor: "#ffffff",
    borderTopRightRadius: 1,
    borderBottomRightRadius: 1,
  },

  /* Phone Interior */
  phoneScreenContent: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  phoneScreenArtwork: {
    position: "absolute",
    inset: 0,
    backgroundImage: "url('/pairing_bg.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    zIndex: 0,
  },
  phoneScreenArtworkOverlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(10, 16, 30, 0.28)",
    zIndex: 1,
  },
  phoneScreenInner: {
    position: "relative",
    zIndex: 2,
    flex: 1,
    padding: "6px 10px 8px",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  fullScreenWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    animation: "fadeIn 0.22s ease-out",
  },

  /* SCREEN 1: PIN Pairing Styles (Photo 1 Match) */
  screen1TopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
  },
  e2eBadgePill: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    border: "1px solid rgba(255, 255, 255, 0.24)",
    borderRadius: 9999,
    padding: "4px 10px",
    fontSize: 10,
    color: "#ffffff",
    fontWeight: 600,
    backdropFilter: "blur(8px)",
  },
  whiteDotMini: {
    width: 5,
    height: 5,
    borderRadius: "50%",
    backgroundColor: "#ffffff",
  },
  threeDotsCircle: {
    width: 26,
    height: 26,
    borderRadius: "50%",
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    border: "1px solid rgba(255, 255, 255, 0.22)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    color: "#ffffff",
    cursor: "pointer",
  },
  brandCenterHeader: {
    textAlign: "center",
    margin: "12px 0 6px",
  },
  brandAirlinkTitle: {
    fontSize: 25,
    fontWeight: 800,
    color: "#ffffff",
    letterSpacing: "-0.03em",
    margin: "0 0 4px",
    fontFamily: "var(--font-sans)",
  },
  brandAirlinkSubtitle: {
    fontSize: 11,
    lineHeight: 1.4,
    color: "rgba(255, 255, 255, 0.88)",
    maxWidth: 215,
    margin: "0 auto",
    fontWeight: 450,
  },
  pinCardExact: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.18)",
    borderRadius: 14,
    padding: "16px 10px 14px",
    textAlign: "center",
    backdropFilter: "blur(14px)",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.18)",
  },
  pinCardTitle: {
    fontSize: 13.5,
    fontWeight: 700,
    color: "#ffffff",
    letterSpacing: "-0.01em",
  },
  pinCardSubtitle: {
    fontSize: 10,
    color: "rgba(255, 255, 255, 0.72)",
    marginTop: 2,
    marginBottom: 12,
  },
  pinBoxesRow: {
    display: "flex",
    gap: 5,
    justifyContent: "center",
  },
  pinBox: {
    width: 33,
    height: 44,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(255, 255, 255, 0.22)",
    borderRadius: 9,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 19,
    fontWeight: 800,
    color: "#ffffff",
    fontFamily: "var(--font-mono)",
    transition: "all 0.15s ease",
  },
  pinBoxActive: {
    border: "1.8px solid #ffffff",
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    boxShadow: "0 0 12px rgba(255, 255, 255, 0.4)",
  },
  pinBoxFilled: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    border: "1px solid rgba(255, 255, 255, 0.4)",
  },
  pinBoxSuccess: {
    borderColor: "rgba(74, 222, 128, 0.7)",
    backgroundColor: "rgba(34, 197, 94, 0.15)",
    color: "#4ade80",
  },
  blinkingCaret: {
    color: "#ffffff",
    fontSize: 15,
    animation: "fadeIn 0.5s infinite alternate",
  },
  pinCardFooter: {
    marginTop: 10,
    fontSize: 9,
    color: "rgba(255, 255, 255, 0.65)",
    fontFamily: "var(--font-sans)",
  },
  connectBtnWide: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    border: "1px solid rgba(255, 255, 255, 0.24)",
    borderRadius: 11,
    padding: "10px 12px",
    textAlign: "center",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "-0.01em",
    backdropFilter: "blur(10px)",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  connectBtnWideSuccess: {
    backgroundColor: "rgba(34, 197, 94, 0.25)",
    borderColor: "rgba(74, 222, 128, 0.5)",
    color: "#4ade80",
  },
  screen1BottomBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  telemetryCardFrosted: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(255, 255, 255, 0.14)",
    borderRadius: 9,
    padding: "8px 11px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  telemetryRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 10,
  },
  telemetryLabel: {
    color: "rgba(255, 255, 255, 0.72)",
  },
  telemetryValue: {
    color: "#ffffff",
    fontWeight: 700,
    fontFamily: "var(--font-sans)",
  },
  greenRelayActivePill: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "rgba(34, 197, 94, 0.22)",
    border: "1px solid rgba(74, 222, 128, 0.38)",
    borderRadius: 8,
    padding: "7px",
    color: "#4ade80",
    fontSize: 11,
    fontWeight: 700,
  },
  greenDotSmall: {
    width: 6.5,
    height: 6.5,
    borderRadius: "50%",
    backgroundColor: "#4ade80",
    boxShadow: "0 0 7px #4ade80",
  },
  relayUrlSubtext: {
    fontSize: 8.5,
    color: "rgba(255, 255, 255, 0.65)",
    textAlign: "center",
    fontFamily: "var(--font-sans)",
  },
  footerBrandSubtext: {
    fontSize: 8,
    color: "rgba(255, 255, 255, 0.5)",
    textAlign: "center",
    fontFamily: "var(--font-sans)",
  },

  /* SCREEN 2: BYOK Vault Styles (Photo 3 Match) */
  byokHeaderCard: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.16)",
    borderRadius: 12,
    padding: "8px 10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backdropFilter: "blur(12px)",
  },
  byokHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  byokHeaderTitle: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "#ffffff",
    letterSpacing: "-0.01em",
  },
  byokHeaderSubtitle: {
    fontSize: 9,
    color: "rgba(255, 255, 255, 0.7)",
  },
  byokHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 5,
  },
  aesPill: {
    fontSize: 8.5,
    fontWeight: 700,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    color: "#ffffff",
    padding: "2px 6px",
    borderRadius: 9999,
  },
  doneBtnPill: {
    fontSize: 10,
    fontWeight: 700,
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    color: "#ffffff",
    padding: "3px 9px",
    borderRadius: 9999,
    cursor: "pointer",
  },
  byokFormSection: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginTop: 4,
  },
  byokSectionLabel: {
    fontSize: 9,
    fontWeight: 800,
    color: "rgba(255, 255, 255, 0.85)",
    letterSpacing: "0.06em",
  },
  providerPillsStack: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  providerRow: {
    display: "flex",
    gap: 4,
  },
  providerPill: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.16)",
    borderRadius: 8,
    padding: "4px 8px",
    fontSize: 9.5,
    color: "#ffffff",
    fontWeight: 600,
  },
  providerPillSelected: {
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    border: "1.5px solid #ffffff",
    borderRadius: 8,
    padding: "4px 8px",
    fontSize: 9.5,
    color: "#ffffff",
    fontWeight: 700,
    boxShadow: "0 0 8px rgba(255, 255, 255, 0.25)",
  },
  byokInputBox: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    borderRadius: 8,
    padding: "6px 8px",
    fontSize: 10.5,
    color: "#ffffff",
    fontFamily: "var(--font-sans)",
  },
  modelChipsRow: {
    display: "flex",
    gap: 4,
  },
  modelChip: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    borderRadius: 6,
    padding: "2px 7px",
    fontSize: 8.5,
    color: "rgba(255, 255, 255, 0.85)",
  },
  byokKeyInputBox: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    borderRadius: 8,
    padding: "6px 8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  keyDots: {
    fontSize: 10,
    color: "#ffffff",
    letterSpacing: 1,
  },
  keyShowBtn: {
    fontSize: 9.5,
    fontWeight: 700,
    color: "#ffffff",
    cursor: "pointer",
  },
  keySecurityNote: {
    fontSize: 8,
    lineHeight: 1.35,
    color: "rgba(255, 255, 255, 0.68)",
    margin: "2px 0 0",
  },
  byokBottomActions: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    marginTop: "auto",
  },
  saveConfigBtn: {
    backgroundColor: "#ffffff",
    color: "#0f172a",
    border: "none",
    borderRadius: 10,
    padding: "8px",
    fontSize: 11.5,
    fontWeight: 800,
    cursor: "pointer",
    textAlign: "center",
  },
  clearKeyBtn: {
    backgroundColor: "rgba(220, 38, 38, 0.28)",
    border: "1px solid rgba(248, 113, 113, 0.35)",
    color: "#fca5a5",
    borderRadius: 10,
    padding: "7px",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "center",
  },

  /* CHAT / ACTIVE REMOTE SCREENS (Photo 2 Match) */
  chatScreenWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    animation: "fadeIn 0.22s ease-out",
  },
  chatScreenHeader: {
    backgroundColor: "rgba(255, 255, 255, 0.09)",
    border: "1px solid rgba(255, 255, 255, 0.16)",
    borderRadius: 11,
    padding: "6px 9px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backdropFilter: "blur(12px)",
  },
  chatHeaderLeft: {
    display: "flex",
    flexDirection: "column",
  },
  chatHeaderTitle: {
    fontSize: 13,
    fontWeight: 800,
    color: "#ffffff",
    letterSpacing: "-0.01em",
  },
  chatHeaderSubtitle: {
    fontSize: 9,
    color: "rgba(255, 255, 255, 0.72)",
  },
  chatHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 5,
  },
  chatModelPill: {
    fontSize: 9.5,
    fontWeight: 700,
    backgroundColor: "rgba(255, 255, 255, 0.14)",
    border: "1px solid rgba(255, 255, 255, 0.22)",
    color: "#ffffff",
    padding: "2px 7px",
    borderRadius: 9999,
  },
  chatCloseBtn: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    color: "#ffffff",
    cursor: "pointer",
  },
  chatFeedScroll: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    margin: "4px 0",
    overflowY: "hidden",
  },
  thinkingCard: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    borderRadius: 10,
    padding: "7px 9px",
    backdropFilter: "blur(10px)",
  },
  thinkingHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 10.5,
    color: "#ffffff",
    fontWeight: 700,
  },
  thinkingTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  thinkingCollapse: {
    fontSize: 9,
    color: "rgba(255, 255, 255, 0.7)",
  },
  thinkingDirective: {
    fontSize: 9.5,
    color: "rgba(255, 255, 255, 0.85)",
    marginTop: 3,
    lineHeight: 1.35,
  },
  agentProseMessage: {
    fontSize: 10.5,
    lineHeight: 1.4,
    color: "#ffffff",
    padding: "1px 2px",
  },
  inlineCodePill: {
    backgroundColor: "rgba(255, 255, 255, 0.14)",
    padding: "1px 5px",
    borderRadius: 4,
    fontFamily: "var(--font-mono)",
    fontSize: 9.5,
  },
  toolExecCard: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    borderRadius: 9,
    padding: "6px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  toolExecHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  toolNameBadge: {
    fontSize: 9.5,
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    border: "1px solid rgba(255, 255, 255, 0.22)",
    padding: "2px 6px",
    borderRadius: 4,
    color: "#ffffff",
  },
  toolExecStatus: {
    fontSize: 9,
    color: "rgba(255, 255, 255, 0.75)",
  },
  toolExecBody: {
    backgroundColor: "rgba(0, 0, 0, 0.28)",
    borderRadius: 6,
    padding: "4px 7px",
    fontSize: 9.5,
    color: "rgba(255, 255, 255, 0.9)",
    fontFamily: "var(--font-mono)",
  },
  codeDiffCard: {
    backgroundColor: "#080e1a",
    border: "1px solid rgba(255, 255, 255, 0.14)",
    borderRadius: 9,
    padding: "6px 8px 16px",
    position: "relative",
    overflow: "hidden",
  },
  codeDiffHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  codeDiffFileName: {
    fontSize: 10.5,
    fontWeight: 800,
    color: "#ffffff",
    fontFamily: "var(--font-mono)",
  },
  codeDiffStats: {
    display: "flex",
    gap: 3,
  },
  badgeAdd: {
    backgroundColor: "rgba(34, 197, 94, 0.25)",
    border: "1px solid rgba(74, 222, 128, 0.4)",
    color: "#4ade80",
    fontSize: 8.5,
    fontWeight: 800,
    padding: "1px 5px",
    borderRadius: 3,
    fontFamily: "var(--font-mono)",
  },
  badgeDel: {
    backgroundColor: "rgba(239, 68, 68, 0.25)",
    border: "1px solid rgba(248, 113, 113, 0.4)",
    color: "#f87171",
    fontSize: 8.5,
    fontWeight: 800,
    padding: "1px 5px",
    borderRadius: 3,
    fontFamily: "var(--font-mono)",
  },
  codeDiffView: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    fontFamily: "var(--font-mono)",
    fontSize: 8.5,
    lineHeight: 1.4,
  },
  diffHeaderLine: {
    color: "#38bdf8",
    opacity: 0.85,
  },
  diffCodeLine: {
    color: "rgba(255, 255, 255, 0.78)",
  },
  diffCodeLineAdd: {
    color: "#4ade80",
    backgroundColor: "rgba(34, 197, 94, 0.22)",
    padding: "1.5px 3px",
    borderRadius: 2,
    display: "block",
    width: "100%",
  },
  diffCodeLineDel: {
    color: "#f87171",
    backgroundColor: "rgba(239, 68, 68, 0.18)",
    padding: "1.5px 3px",
    borderRadius: 2,
    display: "block",
    width: "100%",
  },
  jumpToLiveFloat: {
    position: "absolute",
    bottom: 5,
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    border: "1px solid rgba(255, 255, 255, 0.45)",
    backdropFilter: "blur(8px)",
    borderRadius: 9999,
    padding: "2px 9px",
    fontSize: 8.5,
    fontWeight: 700,
    color: "#ffffff",
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.4)",
  },

  /* Bottom Dock: Chips ABOVE Prompt Input Bar */
  chatBottomDock: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginTop: "auto",
  },
  quickChipsRow: {
    display: "flex",
    gap: 4,
    overflowX: "hidden",
    padding: "1px 0",
  },
  quickChip: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    border: "1px solid rgba(255, 255, 255, 0.22)",
    borderRadius: 9999,
    padding: "4px 9px",
    fontSize: 9,
    fontWeight: 600,
    color: "#ffffff",
    whiteSpace: "nowrap",
    backdropFilter: "blur(6px)",
  },
  promptInputContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.09)",
    border: "1px solid rgba(255, 255, 255, 0.22)",
    borderRadius: 9999,
    padding: "5px 6px 5px 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backdropFilter: "blur(12px)",
  },
  promptPlaceholder: {
    fontSize: 9.5,
    color: "rgba(255, 255, 255, 0.58)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  promptSendArrow: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    backgroundColor: "rgba(255, 255, 255, 0.22)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    color: "#ffffff",
    fontWeight: 700,
  },

  /* Safety Gate Screen 4 */
  safetyGateCard: {
    backgroundColor: "rgba(234, 88, 12, 0.12)",
    border: "1px solid rgba(234, 88, 12, 0.35)",
    borderRadius: 9,
    padding: "7px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  safetyGateHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  safetyGateTitle: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 9.5,
    fontWeight: 800,
    color: "#fb923c",
  },
  safetyCountdownBadge: {
    fontSize: 8.5,
    fontWeight: 800,
    fontFamily: "var(--font-mono)",
    backgroundColor: "rgba(234, 88, 12, 0.3)",
    color: "#fdba74",
    padding: "1px 5px",
    borderRadius: 4,
  },
  safetyCommandBox: {
    backgroundColor: "#030712",
    borderRadius: 5,
    padding: "4px 6px",
    fontFamily: "var(--font-mono)",
    fontSize: 8.5,
    color: "#fdba74",
  },
  approvalButtons: {
    display: "flex",
    gap: 5,
  },
  btnApprove: {
    flex: 1,
    backgroundColor: "#16a34a",
    color: "#ffffff",
    border: "none",
    borderRadius: 6,
    padding: "6px",
    fontSize: 9.5,
    fontWeight: 700,
    cursor: "pointer",
  },
  btnReject: {
    backgroundColor: "rgba(220, 38, 38, 0.2)",
    border: "1px solid rgba(220, 38, 38, 0.4)",
    color: "#fca5a5",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 9.5,
    fontWeight: 700,
    cursor: "pointer",
  },
  approvedBanner: {
    backgroundColor: "rgba(22, 163, 74, 0.25)",
    border: "1px solid rgba(74, 222, 128, 0.45)",
    color: "#4ade80",
    padding: "6px",
    borderRadius: 6,
    textAlign: "center",
    fontSize: 9.5,
    fontWeight: 700,
  },

  /* Diff Viewer Screen 5 */
  filesSummaryCard: {
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    borderRadius: 7,
    padding: "5px 7px",
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  filesSummaryTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  filesSummaryLeft: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    fontSize: 9,
    fontWeight: 700,
    color: "#ffffff",
  },
  reviewBtn: {
    fontSize: 8.5,
    color: "#38bdf8",
    fontWeight: 700,
    cursor: "pointer",
  },
  filesListStack: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  fileRowItem: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 8.5,
  },
  fileNameWhite: {
    color: "rgba(255, 255, 255, 0.85)",
    fontFamily: "var(--font-mono)",
  },

  /* iOS Home Indicator */
  iosHomeIndicator: {
    width: 108,
    height: 4,
    backgroundColor: "rgba(255, 255, 255, 0.65)",
    borderRadius: 9999,
    margin: "6px auto 5px",
  },
};
