"use client";

import React, { useState, useEffect } from "react";
import { AirLinkAgentLogo } from "../ui/AirLinkAgentLogo";
import { WorkstationTuiMockup } from "./WorkstationTuiMockup";

interface FeatureStep {
  id: string;
  stepNumber: string;
  title: string;
  description: string;
}

const features: FeatureStep[] = [
  {
    id: "pin-pairing",
    stepNumber: "01",
    title: "Zero Port-Forwarding Pairing",
    description:
      "No port forwarding, ngrok tunnels, or complex VPN setups. Type a 6-digit ephemeral PIN generated by your local workstation CLI daemon to pair securely over an end-to-end WebSocket relay in 3 seconds.",
  },
  {
    id: "byok-vault",
    stepNumber: "02",
    title: "Client-Side BYOK Key Vault",
    description:
      "Bring Your Own API Keys with zero cloud retention. Store and switch Anthropic, OpenAI, and DeepSeek credentials client-side with AES-256 encryption. Your keys never touch our servers.",
  },
  {
    id: "telemetry",
    stepNumber: "03",
    title: "Real-Time Token Telemetry",
    description:
      "Watch Claude, DeepSeek, and TrueForge agents generate code character-by-character with zero noticeable latency. Full AST syntax highlights, terminal pipes, and ANSI output straight in your pocket.",
  },
  {
    id: "safety-gate",
    stepNumber: "04",
    title: "1-Tap Human-in-the-Loop Approvals",
    description:
      "Never let an autonomous agent accidentally delete production files. Destructive bash executions and critical config edits pause at an encrypted 180s safety gate awaiting your explicit 1-tap mobile authorization.",
  },
  {
    id: "diff-inspector",
    stepNumber: "05",
    title: "Visual Git Diff & AST Viewer",
    description:
      "Review unified multi-file diffs before your agent commits. Line-by-line green additions, red deletions, and folded context blocks formatted cleanly for handheld mobile screens.",
  },
];

export function ScrollFeaturePhoneShowcase() {
  const [activeIndex, setActiveIndex] = useState<number>(0);
  const [countdown, setCountdown] = useState<number>(178);
  const [isApproved, setIsApproved] = useState<boolean>(false);
  const [isPaused, setIsPaused] = useState<boolean>(false);

  // Live PIN entering simulation for the first mobile screen
  const [typedPin, setTypedPin] = useState<string>("");
  const [isPairedSuccess, setIsPairedSuccess] = useState<boolean>(false);

  useEffect(() => {
    if (activeIndex !== 0) return;
    const TARGET_PIN = "834192";
    let step = 0;
    setTypedPin("");
    setIsPairedSuccess(false);

    const typeInterval = setInterval(() => {
      step++;
      if (step <= TARGET_PIN.length) {
        setTypedPin(TARGET_PIN.slice(0, step));
        if (step === TARGET_PIN.length) {
          setIsPairedSuccess(true);
        }
      } else if (step > TARGET_PIN.length + 5) {
        step = 0;
        setTypedPin("");
        setIsPairedSuccess(false);
      }
    }, 460);

    return () => clearInterval(typeInterval);
  }, [activeIndex]);

  // 180s countdown simulation for Safety Gate
  useEffect(() => {
    if (isApproved) return;
    const timer = setInterval(() => {
      setCountdown((prev) => (prev > 1 ? prev - 1 : 180));
    }, 1000);
    return () => clearInterval(timer);
  }, [isApproved]);

  // Auto-advance every 7 seconds when user is not manually hovering
  useEffect(() => {
    if (isPaused) return;
    const interval = setInterval(() => {
      setActiveIndex((prev) => (prev + 1) % features.length);
    }, 7000);
    return () => clearInterval(interval);
  }, [isPaused]);

  const handleApprove = () => {
    setIsApproved(true);
    setTimeout(() => setIsApproved(false), 4000);
  };

  const handlePrev = () => {
    setActiveIndex((prev) => (prev > 0 ? prev - 1 : features.length - 1));
  };

  const handleNext = () => {
    setActiveIndex((prev) => (prev + 1) % features.length);
  };

  return (
    <section
      id="features"
      style={styles.showcaseSection}
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      {/* Main Presentation Container (2 Columns: Left Header + Ladder | Right Phone Mockup) */}
      <div style={styles.stageGrid}>
        {/* LEFT COLUMN: Header + 3-Stair Vertical Ladder */}
        <div style={styles.leftColumn}>
          {/* Left-Aligned Header */}
          <div style={styles.headerContainer}>
            <h2 style={styles.mainTitle}>
              Your Autonomous Agent <br />
              In The Palm of Your Hand.
            </h2>
            <p style={styles.mainSubtitle}>
              Explore the core mobile surfaces designed for high-speed supervision from anywhere.
            </p>
          </div>

          {/* 3-Stair Vertical Ladder (Active unfaded, upper & lower faded) */}
          <div style={styles.ladderColumn}>
            {/* Vertical Staircase Progress Line */}
            <div style={styles.ladderRail}>
              <div
                style={{
                  ...styles.ladderRailIndicator,
                  top: `${(activeIndex / (features.length - 1)) * 82}%`,
                }}
              />
            </div>

          {/* Staircase Item Stack */}
          <div style={styles.ladderItemsWrapper}>
            {features.map((feature, idx) => {
              const diff = idx - activeIndex;
              const isActive = diff === 0;
              const isUpper = diff === -1;
              const isLower = diff === 1;
              const isVisible = isActive || isUpper || isLower;

              if (!isVisible) return null;

              return (
                <div
                  key={feature.id}
                  onClick={() => setActiveIndex(idx)}
                  style={{
                    ...styles.ladderItem,
                    ...(isActive
                      ? styles.ladderItemActive
                      : isUpper
                      ? styles.ladderItemUpper
                      : styles.ladderItemLower),
                  }}
                >
                  <div style={styles.itemHeaderRow}>
                    <span
                      style={{
                        ...styles.stepNumberText,
                        color: isActive ? "#2563eb" : "#94a3b8",
                      }}
                    >
                      {feature.stepNumber}
                    </span>
                  </div>

                  <h3
                    style={{
                      ...styles.ladderTitle,
                      ...(isActive
                        ? styles.ladderTitleActive
                        : styles.ladderTitleFaded),
                    }}
                  >
                    {feature.title}
                  </h3>

                  {isActive && (
                    <div style={styles.activeDetailBox}>
                      <p style={styles.ladderDescription}>{feature.description}</p>
                    </div>
                  )}
                </div>
              );
            })}

            {/* Step Switcher Controls */}
            <div style={styles.stepControlsRow}>
              <button
                type="button"
                onClick={handlePrev}
                style={styles.navArrowBtn}
                title="Previous Feature"
              >
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <path d="M19 12H5M12 19l-7-7 7-7" />
                </svg>
              </button>
              <div style={styles.pillsList}>
                {features.map((_, dotIdx) => (
                  <button
                    key={dotIdx}
                    type="button"
                    onClick={() => setActiveIndex(dotIdx)}
                    style={{
                      ...styles.stepDot,
                      ...(activeIndex === dotIdx ? styles.stepDotActive : {}),
                    }}
                    title={`Feature ${dotIdx + 1}`}
                  />
                ))}
              </div>
              <button
                type="button"
                onClick={handleNext}
                style={styles.navArrowBtn}
                title="Next Feature"
              >
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <path d="M5 12h14M12 5l7 7-7 7" />
                </svg>
              </button>
            </div>
          </div>
        </div>
        </div>

        {/* RIGHT: Diagonal Duo Showcase (Workstation Local TUI + Phone Remote Mockup) */}
        <div style={styles.duoStageColumn}>
          {/* Workstation Local Daemon TUI Window (Diagonally Behind) */}
          <div style={styles.tuiWrapperDiagonal}>
            <WorkstationTuiMockup
              activeIndex={activeIndex}
              typedPin={typedPin}
              isPairedSuccess={isPairedSuccess}
              isApproved={isApproved}
              countdown={countdown}
            />
          </div>

          {/* Realistic Phone Mockup (Diagonally Foreground) */}
          <div style={styles.phoneDeviceFrame}>
            {/* Dynamic Island Notch */}
            <div style={styles.dynamicIsland}>
              <div style={styles.cameraLens} />
              <div style={styles.sensorDot} />
            </div>

            {/* Phone Status Bar */}
            <div style={styles.phoneStatusBar}>
              <span style={styles.statusTime}>9:41</span>
              <div style={styles.statusIcons}>
                <svg width="14" height="10" viewBox="0 0 24 24" fill="#ffffff">
                  <path d="M12 3c-4.97 0-9 4.03-9 9 0 2.12.74 4.07 1.97 5.61L4.35 18.97c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0l1.36-1.36C8.67 19.64 10.26 20 12 20c4.97 0 9-4.03 9-9s-4.03-9-9-9z" />
                </svg>
                <span style={styles.statusBattery}>100%</span>
              </div>
            </div>

            {/* Mobile Screen Interior with Hero Background Artwork */}
            <div style={styles.phoneScreenContent}>
              {/* Hero Panoramic Artwork Background */}
              <div style={styles.phoneScreenArtwork} />
              <div style={styles.phoneScreenArtworkOverlay} />

              {/* Screen Contents Layer */}
              <div style={styles.phoneScreenInner}>
                {/* SCREEN 1: 6-Digit Encrypted PIN Pairing (Matches User Screenshot 1:1) */}
                {activeIndex === 0 && (
                <div key="screen-0" style={styles.fullScreenWrapper}>
                  {/* Top Header Bar */}
                  <div style={styles.pinScreenHeader}>
                    <div style={styles.pinHeaderLeft}>
                      <span style={{ fontSize: 13 }}>🚀</span>
                      <span style={styles.pinHeaderTitle}>AirLink PIN Pairing</span>
                    </div>
                    <span style={styles.pinHeaderMeta}>WebSocket E2E</span>
                  </div>

                  {/* Center Card with Dynamic PIN Typing Simulation */}
                  <div style={styles.pinCenterCardExact}>
                    <div
                      style={{
                        ...styles.pinLockCircleExact,
                        borderColor: isPairedSuccess ? "rgba(34, 197, 94, 0.45)" : "rgba(59, 130, 246, 0.35)",
                        backgroundColor: isPairedSuccess ? "rgba(34, 197, 94, 0.15)" : "rgba(37, 99, 235, 0.18)",
                        transition: "all 0.25s ease",
                      }}
                    >
                      {isPairedSuccess ? (
                        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#4ade80" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                          <polyline points="20 6 9 17 4 12" />
                        </svg>
                      ) : (
                        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#38bdf8" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                          <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
                          <path d="M7 11V7a5 5 0 0 1 10 0v4" />
                        </svg>
                      )}
                    </div>

                    <span style={styles.pinMainTitleExact}>Workstation Session PIN</span>
                    <span
                      style={{
                        ...styles.pinSubtitleExact,
                        color: isPairedSuccess ? "#4ade80" : "#94a3b8",
                        fontWeight: isPairedSuccess ? 700 : 400,
                      }}
                    >
                      {isPairedSuccess ? "✓ Paired to MacBook-Pro-M3 (0.04s)" : "Pairing with MacBook-Pro-M3"}
                    </span>

                    <div style={styles.pinBoxesRowExact}>
                      {[0, 1, 2, 3, 4, 5].map((dIdx) => {
                        const digit = typedPin[dIdx] || "";
                        const isCurrentActive = typedPin.length === dIdx && !isPairedSuccess;
                        return (
                          <div
                            key={dIdx}
                            style={{
                              ...styles.pinBoxExact,
                              borderColor: isPairedSuccess
                                ? "rgba(34, 197, 94, 0.6)"
                                : isCurrentActive
                                ? "#38bdf8"
                                : digit
                                ? "rgba(59, 130, 246, 0.65)"
                                : "rgba(255, 255, 255, 0.12)",
                              boxShadow: isCurrentActive
                                ? "0 0 12px rgba(56, 189, 248, 0.5)"
                                : isPairedSuccess
                                ? "0 0 12px rgba(34, 197, 94, 0.3)"
                                : "0 4px 14px rgba(0, 0, 0, 0.5)",
                              backgroundColor: isPairedSuccess
                                ? "rgba(22, 101, 52, 0.2)"
                                : isCurrentActive
                                ? "rgba(30, 58, 138, 0.25)"
                                : "#0a101f",
                              color: isPairedSuccess ? "#4ade80" : "#ffffff",
                              transition: "all 0.15s ease",
                            }}
                          >
                            {digit ? (
                              <span style={{ animation: "pop-in 180ms ease-out both" }}>{digit}</span>
                            ) : isCurrentActive ? (
                              <span style={{ color: "#38bdf8", animation: "fade-in 400ms infinite alternate", fontSize: 16 }}>|</span>
                            ) : (
                              ""
                            )}
                          </div>
                        );
                      })}
                    </div>

                    <span style={styles.pinExpiryTextExact}>
                      🔒 Ephemeral session • Auto-expires
                    </span>
                  </div>

                  {/* Bottom Stack: Host Info + Green WebSocket Relay Bar */}
                  <div style={styles.screenBottomBlockExact}>
                    <div style={styles.hostInfoCardExact}>
                      <div style={styles.hostInfoRowExact}>
                        <span style={styles.hostInfoLabelExact}>WebSocket Relay:</span>
                        <span style={styles.hostInfoValueExact}>sub-50ms (Direct)</span>
                      </div>
                      <div style={styles.hostInfoRowExact}>
                        <span style={styles.hostInfoLabelExact}>Security:</span>
                        <span style={styles.hostInfoValueExact}>E2E Encrypted</span>
                      </div>
                    </div>

                    <div style={styles.tunnelStatusRowExact}>
                      <span style={styles.tunnelDotExact} />
                      <span style={styles.tunnelTextExact}>WebSocket Relay Active</span>
                    </div>
                  </div>
                </div>
              )}

              {/* SCREEN 2: BYOK Key Vault */}
              {activeIndex === 1 && (
                <div key="screen-1" style={styles.fullScreenWrapper}>
                  <div style={styles.screenHeader}>
                    <div style={styles.headerLeft}>
                      <AirLinkAgentLogo size={16} animated={false} textColor="#ffffff" />
                      <span style={styles.screenHeaderTitle}>Client-Side BYOK Vault</span>
                    </div>
                    <span style={styles.headerMetaText}>AES-256</span>
                  </div>

                  <div style={styles.byokList}>
                    <div style={styles.byokItem}>
                      <div style={styles.byokTopRow}>
                        <span style={styles.byokProviderName}>Anthropic Claude 3.7</span>
                        <span style={styles.byokStatusActive}>● Active</span>
                      </div>
                      <div style={styles.byokKeyMask}>sk-ant-api03-••••••••4f8a</div>
                    </div>

                    <div style={styles.byokItem}>
                      <div style={styles.byokTopRow}>
                        <span style={styles.byokProviderName}>DeepSeek R1 / V3</span>
                        <span style={styles.byokStatusActive}>● Active</span>
                      </div>
                      <div style={styles.byokKeyMask}>sk-dsk-••••••••92b1</div>
                    </div>

                    <div style={styles.byokItem}>
                      <div style={styles.byokTopRow}>
                        <span style={styles.byokProviderName}>OpenAI o3-mini</span>
                        <span style={styles.byokStatusActive}>● Active</span>
                      </div>
                      <div style={styles.byokKeyMask}>sk-proj-••••••••e19c</div>
                    </div>

                    <div style={styles.byokItem}>
                      <div style={styles.byokTopRow}>
                        <span style={styles.byokProviderName}>Google Gemini 2.0</span>
                        <span style={styles.byokStatusActive}>● Active</span>
                      </div>
                      <div style={styles.byokKeyMask}>AIzaSy••••••••7x9b</div>
                    </div>
                  </div>

                  <div style={styles.screenBottomBlock}>
                    <div style={styles.tunnelStatusRow}>
                      <span style={styles.tunnelDot} />
                      <span style={styles.tunnelText}>4 Model Providers Configured</span>
                    </div>
                  </div>
                </div>
              )}

              {/* SCREEN 3: Real-Time Token Telemetry (Upper: User Message + Worked Trace + File Changes | Lower: Terminal) */}
              {activeIndex === 2 && (
                <div key="screen-2" style={styles.splitScreenWrapper}>
                  {/* Top Header */}
                  <div style={styles.screenHeader}>
                    <div style={styles.headerLeft}>
                      <AirLinkAgentLogo size={16} animated={false} textColor="#ffffff" />
                      <span style={styles.screenHeaderTitle}>AirLink Remote</span>
                    </div>
                    <span style={styles.headerMetaText}>DeepSeek-R1</span>
                  </div>

                  {/* UPPER HALF: User Message + Worked Trace + File Changes Card */}
                  <div style={styles.chatUpperSection}>
                    {/* User Prompt Message Card */}
                    <div style={styles.userMessageCard}>
                      Refactor auth middleware to enforce TLS 1.3 and WebSocket heartbeats
                    </div>

                    {/* Worked Trace Header */}
                    <div style={styles.traceWorkedHeader}>
                      <span>Worked for 14s</span>
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <polyline points="9 18 15 12 9 6" />
                      </svg>
                    </div>

                    {/* File Changes Card */}
                    <div style={styles.fileChangesCard}>
                      <div style={styles.fileChangesTopRow}>
                        <div style={styles.fileStatsLeft}>
                          <span>2 files changed</span>
                          <span style={styles.addStat}>+38</span>
                          <span style={styles.delStat}>-14</span>
                          <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2.5" style={{ marginLeft: 3 }}>
                            <polyline points="6 9 12 15 18 9" />
                          </svg>
                        </div>
                        <button type="button" style={styles.reviewBtnMini}>
                          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                            <polyline points="14 2 14 8 20 8" />
                            <line x1="16" y1="13" x2="8" y2="13" />
                            <line x1="16" y1="17" x2="8" y2="17" />
                          </svg>
                          <span>Review</span>
                        </button>
                      </div>

                      {/* File List Items */}
                      <div style={styles.fileListStack}>
                        <div style={styles.fileItemRow}>
                          <span style={styles.reactFileIcon}>⚛️</span>
                          <span style={styles.fileNameText}>session.ts</span>
                          <span style={styles.filePathText}>...apps/web/src/server</span>
                        </div>
                        <div style={styles.fileItemRow}>
                          <span style={styles.tsFileIcon}>⚡</span>
                          <span style={styles.fileNameText}>relay-tunnel.ts</span>
                          <span style={styles.filePathText}>...apps/web/src/server</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* LOWER HALF: Live Token Stream Terminal Widget */}
                  <div style={styles.widgetLowerSection}>
                    <div style={styles.widgetSectionHeader}>
                      <span style={styles.widgetTitle}>Terminal Token Telemetry</span>
                      <span style={styles.widgetMeta}>64.2 tok/s</span>
                    </div>

                    <div style={styles.terminalBoxSplit}>
                      <div style={styles.terminalPrompt}>$ trueforge --agent deepseek-r1</div>
                      <div style={styles.tokenOutput}>
                        <span style={{ color: "#38bdf8" }}>[Task: Refactor auth middleware]</span>
                        <br />
                        <span style={{ color: "#94a3b8" }}>&gt; routes/v1/session.ts</span>
                        <br />
                        <span style={{ color: "#4ade80" }}>+ 12 security rules verified</span>
                        <br />
                        <span style={{ color: "#f8fafc" }}>
                          &gt; Streaming diff...
                          <span style={styles.blinkingCursor}>█</span>
                        </span>
                      </div>
                    </div>

                    <div style={styles.telemetryQuickBar}>
                      <span style={styles.telemetryStat}>Latency: <strong>12ms</strong></span>
                      <span style={styles.telemetryStat}>Buffer: <strong>1.4 KB</strong></span>
                      <span style={styles.telemetryLiveDot}>● Stream Active</span>
                    </div>
                  </div>
                </div>
              )}

              {/* SCREEN 4: 1-Tap Human Approvals (Upper: User Message + Worked Trace + Files | Lower: Safety Gate) */}
              {activeIndex === 3 && (
                <div key="screen-3" style={styles.splitScreenWrapper}>
                  {/* Top Header */}
                  <div style={styles.screenHeader}>
                    <div style={styles.headerLeft}>
                      <AirLinkAgentLogo size={16} animated={false} textColor="#ffffff" />
                      <span style={styles.screenHeaderTitle}>AirLink Remote</span>
                    </div>
                    <span style={styles.countdownBadge}>{countdown}s Gate</span>
                  </div>

                  {/* UPPER HALF: User Message + Worked Trace + File Changes Card */}
                  <div style={styles.chatUpperSection}>
                    {/* User Prompt Message Card */}
                    <div style={styles.userMessageCard}>
                      Purge the build artifacts and run production verification
                    </div>

                    {/* Worked Trace Header */}
                    <div style={styles.traceWorkedHeader}>
                      <span>Worked for 28s</span>
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <polyline points="9 18 15 12 9 6" />
                      </svg>
                    </div>

                    {/* File Changes Card */}
                    <div style={styles.fileChangesCard}>
                      <div style={styles.fileChangesTopRow}>
                        <div style={styles.fileStatsLeft}>
                          <span>1 directory target</span>
                          <span style={styles.delStat}>-1,240</span>
                          <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2.5" style={{ marginLeft: 3 }}>
                            <polyline points="6 9 12 15 18 9" />
                          </svg>
                        </div>
                        <button type="button" style={styles.reviewBtnMini}>
                          <span>⚠️ Review</span>
                        </button>
                      </div>

                      {/* File List Items */}
                      <div style={styles.fileListStack}>
                        <div style={styles.fileItemRow}>
                          <span style={styles.reactFileIcon}>📁</span>
                          <span style={styles.fileNameText}>dist/</span>
                          <span style={styles.filePathText}>...apps/web/dist</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* LOWER HALF: 180s Safety Gate Approval Card */}
                  <div style={styles.widgetLowerSection}>
                    <div style={styles.safetyGateCardSplit}>
                      <div style={styles.safetyHeader}>
                        <span style={styles.safetyIcon}>⚠️</span>
                        <span style={styles.safetyTitle}>Safety Gate Interception</span>
                      </div>

                      <div style={styles.commandCodeBlock}>
                        <code>rm -rf dist/ &amp;&amp; pnpm build:prod</code>
                      </div>

                      {isApproved ? (
                        <div style={styles.approvedSuccessBanner}>
                          <span>✓ Command Authorized &amp; Executing...</span>
                        </div>
                      ) : (
                        <div style={styles.approvalButtonsRow}>
                          <button
                            type="button"
                            onClick={handleApprove}
                            style={styles.approveBtn}
                          >
                            <span>Approve (1-Tap)</span>
                          </button>
                          <button type="button" style={styles.rejectBtn}>
                            <span>Reject</span>
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {/* SCREEN 5: Visual Git Diff & AST Viewer (Matches User's Exact Screenshot!) */}
              {activeIndex === 4 && (
                <div key="screen-4" style={styles.splitScreenWrapper}>
                  {/* Top Header */}
                  <div style={styles.screenHeader}>
                    <div style={styles.headerLeft}>
                      <AirLinkAgentLogo size={16} animated={false} textColor="#ffffff" />
                      <span style={styles.screenHeaderTitle}>AirLink Remote</span>
                    </div>
                    <span style={styles.headerMetaText}>+92 / -35</span>
                  </div>

                  {/* UPPER HALF: User Message + Worked for 52s + File Changes Card (Exact Screenshot Match) */}
                  <div style={styles.chatUpperSection}>
                    {/* User Prompt Message Card */}
                    <div style={styles.userMessageCard}>
                      also the hero text let us have it all black and i have some gsap effect like something appearing sort of
                    </div>

                    {/* Worked for 52s Trace Header */}
                    <div style={styles.traceWorkedHeader}>
                      <span>Worked for 52s</span>
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <polyline points="9 18 15 12 9 6" />
                      </svg>
                    </div>

                    {/* File Changes Card */}
                    <div style={styles.fileChangesCard}>
                      <div style={styles.fileChangesTopRow}>
                        <div style={styles.fileStatsLeft}>
                          <span>2 files changed</span>
                          <span style={styles.addStat}>+92</span>
                          <span style={styles.delStat}>-35</span>
                          <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2.5" style={{ marginLeft: 3 }}>
                            <polyline points="6 9 12 15 18 9" />
                          </svg>
                        </div>
                        <button type="button" style={styles.reviewBtnMini}>
                          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                            <polyline points="14 2 14 8 20 8" />
                            <line x1="16" y1="13" x2="8" y2="13" />
                            <line x1="16" y1="17" x2="8" y2="17" />
                          </svg>
                          <span>Review</span>
                        </button>
                      </div>

                      {/* File List Items */}
                      <div style={styles.fileListStack}>
                        <div style={styles.fileItemRow}>
                          <span style={styles.reactFileIcon}>⚛️</span>
                          <span style={styles.fileNameText}>PanoramicLandscapeHero.tsx</span>
                          <span style={styles.filePathText}>...gent-harness/apps/web/src/components/hero</span>
                        </div>
                        <div style={styles.fileItemRow}>
                          <span style={styles.markdownFileIcon}>M↓</span>
                          <span style={styles.fileNameText}>progress-tracker.md</span>
                          <span style={styles.filePathText}>/c:/Users/Tyra/agent-harness/context</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* LOWER HALF: Visual Git Diff Inspector Widget */}
                  <div style={styles.widgetLowerSection}>
                    <div style={styles.diffFilePathSplit}>src/components/hero/PanoramicLandscapeHero.tsx</div>
                    <div style={styles.diffContainerSplit}>
                      <div style={styles.diffLineDel}>
                        - color: &quot;transparent&quot;, backgroundClip: &quot;text&quot;,
                      </div>
                      <div style={styles.diffLineAdd}>
                        + color: &quot;#0f172a&quot;, fontWeight: 900,
                      </div>
                      <div style={styles.diffLineAdd}>
                        + gsap.fromTo(&quot;.hero-word&quot;, &#123; filter: &quot;blur(12px)&quot;, y: 48 &#125;,
                      </div>
                      <div style={styles.diffLineNeutral}>
                        &nbsp;&nbsp;&#123; filter: &quot;blur(0px)&quot;, y: 0, stagger: 0.065 &#125;);
                      </div>
                      <div style={styles.diffLineAdd}>
                        + emitTelemetry(&quot;gsap_reveal_completed&quot;);
                      </div>
                    </div>

                    <div style={styles.diffFooterRow}>
                      <span style={styles.diffBranchName}>feat/gsap-cinematic-reveal</span>
                      <span style={styles.diffReadyText}>✓ Ready to commit</span>
                    </div>
                  </div>
                </div>
              )}
              </div>
            </div>

            {/* Phone Bottom Home Indicator */}
            <div style={styles.phoneHomeBar} />
          </div>
        </div>
      </div>
    </section>
  );
}

const styles: Record<string, React.CSSProperties> = {
  showcaseSection: {
    backgroundColor: "#ffffff",
    color: "#0f172a",
    padding: "60px 24px 60px",
    position: "relative",
    zIndex: 10,
    borderTop: "1px solid #f1f5f9",
  },
  leftColumn: {
    display: "flex",
    flexDirection: "column",
    gap: 32,
  },
  headerContainer: {
    maxWidth: "100%",
    margin: 0,
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 12,
  },
  mainTitle: {
    fontFamily: "var(--font-display)",
    fontSize: "clamp(32px, 3.8vw, 48px)",
    fontWeight: 900,
    lineHeight: 1.12,
    letterSpacing: -1.4,
    color: "#0f172a",
    margin: 0,
  },
  mainSubtitle: {
    fontSize: "clamp(15px, 1.35vw, 17px)",
    color: "#475569",
    lineHeight: 1.6,
    maxWidth: 520,
    fontWeight: 500,
    margin: 0,
  },
  stageGrid: {
    maxWidth: 1260,
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "1fr 1.15fr",
    gap: 40,
    alignItems: "center",
  },
  ladderColumn: {
    display: "flex",
    alignItems: "flex-start",
    gap: 26,
    minHeight: 440,
    position: "relative",
  },
  ladderRail: {
    width: 2,
    height: 320,
    backgroundColor: "#e2e8f0",
    borderRadius: 9999,
    position: "relative",
    marginTop: 14,
    flexShrink: 0,
  },
  ladderRailIndicator: {
    position: "absolute",
    left: -4,
    width: 10,
    height: 36,
    backgroundColor: "#2563eb",
    borderRadius: 9999,
    transition: "top 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
  },
  ladderItemsWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
    width: "100%",
  },
  ladderItem: {
    cursor: "pointer",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    display: "flex",
    flexDirection: "column",
  },
  ladderItemActive: {
    opacity: 1,
    transform: "translateY(0) scale(1)",
  },
  ladderItemUpper: {
    opacity: 0.28,
    transform: "translateY(-4px) scale(0.95)",
    filter: "blur(0.4px)",
  },
  ladderItemLower: {
    opacity: 0.28,
    transform: "translateY(4px) scale(0.95)",
    filter: "blur(0.4px)",
  },
  itemHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 5,
  },
  stepNumberText: {
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: 0.5,
  },
  ladderTitle: {
    fontFamily: "var(--font-display)",
    margin: 0,
    lineHeight: 1.2,
    letterSpacing: -0.6,
  },
  ladderTitleActive: {
    fontSize: "clamp(26px, 2.5vw, 33px)",
    fontWeight: 900,
    color: "#0f172a",
  },
  ladderTitleFaded: {
    fontSize: "clamp(18px, 1.8vw, 21px)",
    fontWeight: 700,
    color: "#64748b",
  },
  activeDetailBox: {
    marginTop: 10,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    animation: "fadeIn 0.25s ease-out",
  },
  ladderDescription: {
    fontSize: 15,
    color: "#475569",
    lineHeight: 1.65,
    maxWidth: 520,
    fontWeight: 450,
  },
  stepControlsRow: {
    marginTop: 14,
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  navArrowBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
    borderRadius: "50%",
    backgroundColor: "#f1f5f9",
    border: "1px solid #e2e8f0",
    color: "#334155",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  pillsList: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  stepDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    backgroundColor: "#cbd5e1",
    border: "none",
    padding: 0,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  stepDotActive: {
    width: 24,
    backgroundColor: "#2563eb",
    borderRadius: 9999,
  },
  duoStageColumn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    width: "100%",
    padding: "10px 0",
  },
  tuiWrapperDiagonal: {
    position: "relative",
    marginRight: "-68px",
    zIndex: 1,
    transform: "translateY(-14px) rotate(-1.5deg)",
    transition: "all 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
    maxWidth: 340,
    width: "100%",
  },
  phoneDeviceFrame: {
    position: "relative",
    zIndex: 2,
    width: 295,
    height: 575,
    backgroundColor: "#000000",
    borderRadius: 42,
    border: "9px solid #1e293b",
    boxShadow: "-12px 25px 60px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(0, 0, 0, 0.25)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    transform: "translateY(12px) rotate(1deg)",
    transition: "all 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
  },
  dynamicIsland: {
    position: "absolute",
    top: 9,
    left: "50%",
    transform: "translateX(-50%)",
    width: 86,
    height: 20,
    backgroundColor: "#000000",
    borderRadius: 20,
    zIndex: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 12px",
  },
  cameraLens: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    backgroundColor: "#1e293b",
  },
  sensorDot: {
    width: 4,
    height: 4,
    borderRadius: "50%",
    backgroundColor: "#0f172a",
  },
  phoneStatusBar: {
    height: 36,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 22px",
    color: "#ffffff",
    fontSize: 11.5,
    fontWeight: 700,
    zIndex: 15,
  },
  statusTime: {
    fontFamily: "var(--font-sans)",
  },
  statusIcons: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  statusBattery: {
    fontSize: 9.5,
    fontFamily: "var(--font-mono)",
  },
  phoneScreenContent: {
    flex: 1,
    backgroundColor: "#090d16",
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  phoneScreenArtwork: {
    position: "absolute",
    inset: 0,
    backgroundImage: "url('/screenshot-hero.png')",
    backgroundSize: "cover",
    backgroundPosition: "center center",
    backgroundRepeat: "no-repeat",
    filter: "contrast(1.2) saturate(1.15) brightness(0.68)",
    zIndex: 0,
  },
  phoneScreenArtworkOverlay: {
    position: "absolute",
    inset: 0,
    background:
      "radial-gradient(ellipse at center, rgba(9, 13, 22, 0.45) 0%, rgba(9, 13, 22, 0.85) 100%)",
    backdropFilter: "blur(1.5px)",
    WebkitBackdropFilter: "blur(1.5px)",
    zIndex: 1,
  },
  phoneScreenInner: {
    position: "relative",
    zIndex: 2,
    flex: 1,
    padding: "10px 10px 12px",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  fullScreenWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    animation: "fadeIn 0.22s ease-out",
  },
  splitScreenWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 7,
    animation: "fadeIn 0.22s ease-out",
  },
  screenHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: 8,
    padding: "6px 10px",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 7,
  },
  headerStatusDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    backgroundColor: "#10b981",
    boxShadow: "0 0 6px #10b981",
  },
  warningDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    backgroundColor: "#f59e0b",
    boxShadow: "0 0 6px #f59e0b",
  },
  screenHeaderTitle: {
    fontSize: 11.5,
    fontWeight: 700,
    color: "#f8fafc",
  },
  headerMetaText: {
    fontSize: 10.5,
    fontFamily: "var(--font-mono)",
    color: "#94a3b8",
    fontWeight: 600,
  },
  countdownBadge: {
    fontSize: 10,
    fontFamily: "var(--font-mono)",
    backgroundColor: "rgba(245, 158, 11, 0.2)",
    color: "#fbbf24",
    padding: "2px 6px",
    borderRadius: 4,
    fontWeight: 800,
  },
  chatUpperSection: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.07)",
    borderRadius: 10,
    padding: "8px 8px 9px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  userMessageCard: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: 10,
    padding: "7px 9px",
    color: "#f1f5f9",
    fontSize: 10,
    lineHeight: 1.38,
    fontWeight: 450,
  },
  traceWorkedHeader: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    color: "#94a3b8",
    fontSize: 9.5,
    fontFamily: "var(--font-mono)",
    fontWeight: 600,
    padding: "2px 2px 0",
    cursor: "pointer",
  },
  fileChangesCard: {
    backgroundColor: "#030712",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    borderRadius: 8,
    padding: "7px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  fileChangesTopRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fileStatsLeft: {
    display: "flex",
    alignItems: "center",
    fontSize: 9.5,
    fontWeight: 600,
    color: "#f8fafc",
  },
  addStat: {
    color: "#4ade80",
    marginLeft: 4,
    fontFamily: "var(--font-mono)",
    fontWeight: 700,
  },
  delStat: {
    color: "#f87171",
    marginLeft: 3,
    fontFamily: "var(--font-mono)",
    fontWeight: 700,
  },
  reviewBtnMini: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    borderRadius: 5,
    padding: "2px 6px",
    color: "#cbd5e1",
    fontSize: 9,
    fontWeight: 600,
    cursor: "pointer",
  },
  fileListStack: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  fileItemRow: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 9.5,
    overflow: "hidden",
  },
  reactFileIcon: {
    fontSize: 10,
  },
  tsFileIcon: {
    fontSize: 10,
    color: "#38bdf8",
  },
  markdownFileIcon: {
    fontSize: 8.5,
    fontFamily: "var(--font-mono)",
    color: "#38bdf8",
    fontWeight: 800,
    backgroundColor: "rgba(56, 189, 248, 0.15)",
    padding: "1px 3px",
    borderRadius: 2,
  },
  fileNameText: {
    fontWeight: 700,
    color: "#f8fafc",
    whiteSpace: "nowrap",
  },
  filePathText: {
    color: "#64748b",
    fontSize: 8,
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  widgetLowerSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  widgetSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 2px",
  },
  widgetTitle: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "#f8fafc",
  },
  widgetMeta: {
    fontSize: 9.5,
    fontFamily: "var(--font-mono)",
    color: "#38bdf8",
    fontWeight: 700,
  },
  terminalBoxSplit: {
    flex: 1,
    backgroundColor: "#030712",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    borderRadius: 8,
    padding: "7px 8px",
    fontFamily: "var(--font-mono)",
    fontSize: 9.5,
    lineHeight: 1.4,
    overflowY: "auto",
  },
  terminalPrompt: {
    color: "#fb923c",
    fontWeight: 700,
    marginBottom: 3,
  },
  tokenOutput: {
    color: "#e2e8f0",
  },
  blinkingCursor: {
    color: "#38bdf8",
  },
  telemetryQuickBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: 6,
    padding: "4px 8px",
    fontSize: 9,
    color: "#94a3b8",
  },
  telemetryStat: {
    fontFamily: "var(--font-mono)",
  },
  telemetryLiveDot: {
    color: "#34d399",
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
  },
  safetyGateCardSplit: {
    flex: 1,
    backgroundColor: "rgba(234, 88, 12, 0.08)",
    border: "1px solid rgba(234, 88, 12, 0.3)",
    borderRadius: 10,
    padding: "9px 8px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 5,
  },
  safetyHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  safetyIcon: {
    fontSize: 13,
  },
  safetyTitle: {
    fontSize: 11,
    fontWeight: 800,
    color: "#ea580c",
  },
  commandCodeBlock: {
    backgroundColor: "#030712",
    border: "1px solid rgba(234, 88, 12, 0.25)",
    borderRadius: 6,
    padding: "5px 7px",
    fontFamily: "var(--font-mono)",
    fontSize: 9.5,
    color: "#fdba74",
    overflowX: "auto",
  },
  approvalButtonsRow: {
    display: "flex",
    gap: 6,
  },
  approveBtn: {
    flex: 1,
    backgroundColor: "#16a34a",
    color: "#ffffff",
    border: "none",
    borderRadius: 6,
    padding: "8px",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
  },
  rejectBtn: {
    backgroundColor: "rgba(220, 38, 38, 0.2)",
    color: "#f87171",
    border: "1px solid rgba(220, 38, 38, 0.4)",
    borderRadius: 6,
    padding: "8px 12px",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
  },
  approvedSuccessBanner: {
    backgroundColor: "rgba(22, 163, 74, 0.2)",
    border: "1px solid rgba(22, 163, 74, 0.4)",
    borderRadius: 7,
    padding: "8px",
    textAlign: "center",
    color: "#4ade80",
    fontSize: 10.5,
    fontWeight: 700,
  },
  diffFilePathSplit: {
    fontFamily: "var(--font-mono)",
    fontSize: 9.5,
    color: "#94a3b8",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    padding: "3px 6px",
    borderRadius: 4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  diffContainerSplit: {
    flex: 1,
    backgroundColor: "#030712",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: 7,
    padding: 7,
    fontFamily: "var(--font-mono)",
    fontSize: 9,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    overflowY: "auto",
  },
  diffLineDel: {
    color: "#f87171",
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    padding: "2px 4px",
    borderRadius: 3,
  },
  diffLineAdd: {
    color: "#4ade80",
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    padding: "2px 4px",
    borderRadius: 3,
  },
  diffLineNeutral: {
    color: "#94a3b8",
    padding: "2px 4px",
  },
  diffFooterRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    padding: "4px 8px",
    borderRadius: 5,
    fontSize: 9.5,
  },
  diffBranchName: {
    color: "#94a3b8",
    fontFamily: "var(--font-mono)",
  },
  diffReadyText: {
    color: "#38bdf8",
    fontWeight: 600,
  },
  pinScreenHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.09)",
    borderRadius: 9,
    padding: "8px 12px",
  },
  pinHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: 7,
  },
  pinHeaderTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#ffffff",
  },
  pinHeaderMeta: {
    fontSize: 11,
    fontFamily: "var(--font-mono)",
    color: "#94a3b8",
    fontWeight: 600,
  },
  pinCenterCardExact: {
    backgroundColor: "#0c1322",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: 16,
    padding: "24px 14px",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    margin: "12px 0",
  },
  pinLockCircleExact: {
    width: 48,
    height: 48,
    borderRadius: "50%",
    backgroundColor: "rgba(37, 99, 235, 0.18)",
    border: "1.5px solid rgba(59, 130, 246, 0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  pinMainTitleExact: {
    fontSize: 15,
    fontWeight: 800,
    color: "#ffffff",
    letterSpacing: -0.2,
  },
  pinSubtitleExact: {
    fontSize: 11.5,
    color: "#94a3b8",
    marginTop: 4,
    marginBottom: 14,
  },
  pinBoxesRowExact: {
    display: "flex",
    gap: 5.5,
    justifyContent: "center",
  },
  pinBoxExact: {
    width: 35,
    height: 44,
    backgroundColor: "#0a101f",
    border: "1.5px solid rgba(59, 130, 246, 0.55)",
    borderRadius: 8,
    color: "#ffffff",
    fontFamily: "var(--font-mono)",
    fontSize: 20,
    fontWeight: 900,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 14px rgba(0, 0, 0, 0.5)",
  },
  pinExpiryTextExact: {
    fontSize: 10,
    color: "#64748b",
    fontFamily: "var(--font-mono)",
    marginTop: 14,
  },
  screenBottomBlockExact: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  hostInfoCardExact: {
    backgroundColor: "#0c1322",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: 9,
    padding: "10px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  hostInfoRowExact: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 11,
  },
  hostInfoLabelExact: {
    color: "#94a3b8",
    fontSize: 10.5,
  },
  hostInfoValueExact: {
    color: "#ffffff",
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    fontSize: 11,
  },
  tunnelStatusRowExact: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    justifyContent: "center",
    backgroundColor: "rgba(6, 78, 59, 0.35)",
    border: "1px solid rgba(16, 185, 129, 0.35)",
    borderRadius: 8,
    padding: "9px 12px",
  },
  tunnelDotExact: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    backgroundColor: "#10b981",
    boxShadow: "0 0 8px #10b981",
  },
  tunnelTextExact: {
    fontSize: 11.5,
    color: "#34d399",
    fontWeight: 700,
  },
  tunnelStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    justifyContent: "center",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    border: "1px solid rgba(16, 185, 129, 0.25)",
    borderRadius: 7,
    padding: "8px 10px",
  },
  byokList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    margin: "10px 0",
  },
  byokItem: {
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: 8,
    padding: "8px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  byokTopRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  byokProviderName: {
    fontSize: 11,
    fontWeight: 700,
    color: "#f8fafc",
  },
  byokStatusActive: {
    fontSize: 9.5,
    fontFamily: "var(--font-mono)",
    color: "#34d399",
    fontWeight: 700,
  },
  byokKeyMask: {
    fontSize: 10,
    fontFamily: "var(--font-mono)",
    color: "#94a3b8",
    backgroundColor: "#030712",
    padding: "3px 6px",
    borderRadius: 4,
  },
  phoneHomeBar: {
    width: 100,
    height: 3.5,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    borderRadius: 9999,
    margin: "8px auto 5px",
  },
};
