version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "tyraakj"
      - "kunalshah017"
    labels:
      - "dependencies"
      - "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "tyraakj"
      - "kunalshah017"
    labels:
      - "ci"
