version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "tyraakj"
      - "kunalshah017"
    labels:
      - "dependencies"
      - "chore"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "tyraakj"
      - "kunalshah017"
    labels:
      - "ci"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
